services:
  aerospike:    
    image:  aero-102_mnr
    container_name: aero-102-mnr-1-1
    
    volumes:
      - ${PWD}:/etc/aerospike
     
    command: --config-file /etc/aerospike/aerospike.conf
 
    networks:
      - aspk-network
    restart: unless-stopped

networks:
  aspk-network:
    driver: bridge
